// counter/AngularCounter/src/app/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
})
export class CounterComponent {
  counter = 0

  addOne() {
    this.counter += 1;
  }

  minusOne() {
    this.counter -= 1;
  }
}

<div class="container">
    <button (click)="minusOne()">-1</button>
    <p>{{counter}}</p>
    <button (click)="addOne()">+1</button>
</div>
<style scoped>
    .container {
        display: flex;
        align-items: center;
        gap: 1rem;
        padding: 1rem 2rem;
        border-radius: 10%;
        background: linear-gradient(90deg, rgba(131,58,180,1) 0%, rgba(253,29,29,1) 50%, rgba(252,176,69,1) 100%);
        background-size: 200% 200%;
        animation: wave 5s ease infinite;
    }

    @keyframes wave {
        0%{background-position:0% 50%}
        50%{background-position:100% 50%}
        100%{background-position:0% 50%}
    }
    button, p {
        padding: 2rem 3rem;
        border-radius: 10%;
        font-size: 2rem;
        color: white;
    }

    button {        
        background: rgba(9,9,121,1);
        transition: background 500ms;
    }
    button:hover {
        outline: 5px solid black;
        background: #00d4ff;
    }
    p {
        font-size: 3rem;
        font-weight: bold;
    }
</style>

// counter/VueCounter/src/components/Counter.vue
<script setup>
import { ref } from "vue";
const counter = ref(0);
const minusOne = () => (counter.value -= 1);
const addOne = () => (counter.value += 1);
</script>

<template>
  <div class="container">
    <button @click="minusOne">-1</button>
    <p>{{ counter }}</p>
    <button @click="addOne">+1</button>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 4rem 3rem;
  border-radius: 10%;
  background: linear-gradient(
    90deg,
    rgba(131, 58, 180, 1) 0%,
    rgba(253, 29, 29, 1) 50%,
    rgba(252, 176, 69, 1) 100%
  );
  background-size: 200% 200%;
  animation: wave 5s ease infinite;
}

@keyframes wave {
  0% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
  100% {
    background-position: 0% 50%;
  }
}
button,
p {
  padding: 2rem 3rem;
  border-radius: 10%;
  font-size: 2rem;
  color: white;
}

button {
  background: rgba(9, 9, 121, 1);
  transition: background 500ms;
}
button:hover {
  outline: 5px solid black;
  background: #00d4ff;
}
p {
  font-size: 3rem;
  font-weight: bold;
}
</style>
